"""add template_id to analysis_jobs"""

revision = '2615b380e426'
down_revision = '8536a051865c'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('analysis_jobs', sa.Column('template_id', sa.UUID(), nullable=True))
    op.create_foreign_key(op.f('fk_analysis_jobs_template_id_templates'), 'analysis_jobs', 'templates', ['template_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_analysis_jobs_template_id_templates'), 'analysis_jobs', type_='foreignkey')
    op.drop_column('analysis_jobs', 'template_id')
    # ### end Alembic commands ###
