"""add report generation runs drafts and events tables"""

revision = '5a556853a0e7'
down_revision = '838ba1ab5f45'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_generation_runs',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_ref_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), nullable=False),
    sa.Column('current_node', sa.String(length=64), nullable=True),
    sa.Column('agent_runtime', sa.String(length=64), server_default='agentcore', nullable=False),
    sa.Column('graph_version', sa.String(length=64), nullable=False),
    sa.Column('context_agent_version', sa.String(length=64), nullable=True),
    sa.Column('research_agent_version', sa.String(length=64), nullable=True),
    sa.Column('critic_agent_version', sa.String(length=64), nullable=True),
    sa.Column('report_agent_version', sa.String(length=64), nullable=True),
    sa.Column('qa_agent_version', sa.String(length=64), nullable=True),
    sa.Column('model_config_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('retry_budget_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('failure_code', sa.String(length=128), nullable=True),
    sa.Column('failure_detail', sa.Text(), nullable=True),
    sa.Column('trace_id', sa.String(length=255), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['patient_ref_id'], ['patient_refs.id'], name=op.f('fk_report_generation_runs_patient_ref_id_patient_refs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_report_generation_runs_session_id_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_report_generation_runs_therapist_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_generation_runs'))
    )
    op.create_table('report_drafts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('generation_run_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_ref_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.String(length=32), server_default='DRAFT', nullable=False),
    sa.Column('soap_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('reasoning_summary_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('claims_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('evidence_trace_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('validation_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('quality_scores_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['generation_run_id'], ['report_generation_runs.id'], name=op.f('fk_report_drafts_generation_run_id_report_generation_runs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patient_ref_id'], ['patient_refs.id'], name=op.f('fk_report_drafts_patient_ref_id_patient_refs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_report_drafts_session_id_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_report_drafts_therapist_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_drafts'))
    )
    op.create_table('report_generation_events',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('run_id', sa.UUID(), nullable=False),
    sa.Column('node_name', sa.String(length=64), nullable=False),
    sa.Column('event_type', sa.String(length=64), nullable=False),
    sa.Column('decision', sa.String(length=64), nullable=True),
    sa.Column('retry_count', sa.Integer(), nullable=True),
    sa.Column('duration_ms', sa.BigInteger(), nullable=True),
    sa.Column('token_usage_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('metadata_json', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['run_id'], ['report_generation_runs.id'], name=op.f('fk_report_generation_events_run_id_report_generation_runs'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_generation_events'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('report_generation_events')
    op.drop_table('report_drafts')
    op.drop_table('report_generation_runs')
    # ### end Alembic commands ###
