"""add ontology and insight map tables"""

revision = '838ba1ab5f45'
down_revision = 'cb758bd5da5f'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('ontology_concepts',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('concept_key', sa.String(length=100), nullable=False),
    sa.Column('label', sa.String(length=255), nullable=False),
    sa.Column('synonyms', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('language_area', sa.String(length=100), nullable=True),
    sa.Column('concept_type', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_concepts')),
    sa.UniqueConstraint('concept_key', name=op.f('uq_ontology_concepts_concept_key'))
    )
    op.create_table('ontology_edges',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('source_concept_id', sa.UUID(), nullable=False),
    sa.Column('target_concept_id', sa.UUID(), nullable=False),
    sa.Column('relation_type', sa.String(length=50), nullable=False),
    sa.Column('evidence_source_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('confidence', sa.Numeric(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['source_concept_id'], ['ontology_concepts.id'], name=op.f('fk_ontology_edges_source_concept_id_ontology_concepts'), ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['target_concept_id'], ['ontology_concepts.id'], name=op.f('fk_ontology_edges_target_concept_id_ontology_concepts'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_ontology_edges'))
    )
    op.create_table('patient_metric_trends',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_ref_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('metric', sa.String(length=100), nullable=False),
    sa.Column('trend_json', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_ref_id'], ['patient_refs.id'], name=op.f('fk_patient_metric_trends_patient_ref_id_patient_refs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_patient_metric_trends_therapist_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patient_metric_trends'))
    )
    op.create_table('soap_case_indexes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_ref_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('language_area', sa.String(length=100), nullable=True),
    sa.Column('metric', sa.String(length=100), nullable=True),
    sa.Column('observed_issue', sa.String(length=255), nullable=True),
    sa.Column('intervention', sa.String(length=255), nullable=True),
    sa.Column('age_band', sa.String(length=50), nullable=True),
    sa.Column('summary', sa.Text(), nullable=False),
    sa.Column('concept_ids', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_ref_id'], ['patient_refs.id'], name=op.f('fk_soap_case_indexes_patient_ref_id_patient_refs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_soap_case_indexes_report_id_reports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_soap_case_indexes_session_id_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_soap_case_indexes_therapist_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_soap_case_indexes'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('soap_case_indexes')
    op.drop_table('patient_metric_trends')
    op.drop_table('ontology_edges')
    op.drop_table('ontology_concepts')
    # ### end Alembic commands ###
