"""add_patients_table"""

revision = 'b13f13eb09be'
down_revision = 'ee74ebb16930'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("DROP TYPE IF EXISTS patient_status")
    op.create_table('patients',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('patient_ref_id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('birth_date', sa.Date(), nullable=True),
    sa.Column('gender', sa.String(length=1), nullable=True),
    sa.Column('memo', sa.Text(), nullable=True),
    sa.Column('status', sa.Enum('ACTIVE', 'DELETED', name='patient_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_ref_id'], ['patient_refs.id'], name=op.f('fk_patients_patient_ref_id_patient_refs'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_patients')),
    sa.UniqueConstraint('patient_ref_id', name=op.f('uq_patients_patient_ref_id'))
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_refs', sa.Column('gender', sa.VARCHAR(length=1), autoincrement=False, nullable=True))
    op.add_column('patient_refs', sa.Column('birth_date', sa.DATE(), autoincrement=False, nullable=True))
    op.add_column('patient_refs', sa.Column('name', sa.VARCHAR(length=100), autoincrement=False, nullable=False))
    op.add_column('patient_refs', sa.Column('status', postgresql.ENUM('ACTIVE', 'DELETED', name='patient_status'), server_default=sa.text("'ACTIVE'::patient_status"), autoincrement=False, nullable=False))
    op.add_column('patient_refs', sa.Column('memo', sa.TEXT(), autoincrement=False, nullable=True))
    op.drop_table('patients')
    # ### end Alembic commands ###
