"""add_report_chat_tables"""

revision = 'cb758bd5da5f'
down_revision = '2615b380e426'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('report_chat_threads',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('session_id', sa.UUID(), nullable=False),
    sa.Column('patient_ref_id', sa.UUID(), nullable=False),
    sa.Column('therapist_id', sa.UUID(), nullable=False),
    sa.Column('status', sa.Enum('ACTIVE', 'CLOSED', name='report_chat_thread_status'), server_default='ACTIVE', nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['patient_ref_id'], ['patient_refs.id'], name=op.f('fk_report_chat_threads_patient_ref_id_patient_refs'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_chat_threads_report_id_reports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['session_id'], ['sessions.id'], name=op.f('fk_report_chat_threads_session_id_sessions'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['therapist_id'], ['users.id'], name=op.f('fk_report_chat_threads_therapist_id_users'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_chat_threads'))
    )
    op.create_table('report_chat_messages',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('content', sa.Text(), nullable=False),
    sa.Column('intent', postgresql.JSONB(astext_type=sa.Text()), nullable=True),
    sa.Column('tool_calls', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['thread_id'], ['report_chat_threads.id'], name=op.f('fk_report_chat_messages_thread_id_report_chat_threads'), ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_chat_messages'))
    )
    op.create_table('report_patch_proposals',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('thread_id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('base_report_version', sa.Integer(), nullable=False),
    sa.Column('target_section', sa.String(length=20), nullable=False),
    sa.Column('original_text', sa.Text(), nullable=False),
    sa.Column('proposed_text', sa.Text(), nullable=False),
    sa.Column('rationale', sa.Text(), nullable=True),
    sa.Column('evidence_refs', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('status', sa.Enum('PENDING', 'APPLIED', 'REJECTED', name='report_patch_status'), server_default='PENDING', nullable=False),
    sa.Column('created_by_message_id', sa.UUID(), nullable=True),
    sa.Column('applied_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['created_by_message_id'], ['report_chat_messages.id'], name=op.f('fk_report_patch_proposals_created_by_message_id_report_chat_messages'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_patch_proposals_report_id_reports'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['thread_id'], ['report_chat_threads.id'], name=op.f('fk_report_patch_proposals_thread_id_report_chat_threads'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_patch_proposals'))
    )
    op.create_table('report_draft_revisions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('report_id', sa.UUID(), nullable=False),
    sa.Column('patch_proposal_id', sa.UUID(), nullable=True),
    sa.Column('version_before', sa.Integer(), nullable=False),
    sa.Column('version_after', sa.Integer(), nullable=False),
    sa.Column('changed_sections', postgresql.JSONB(astext_type=sa.Text()), nullable=False),
    sa.Column('approved_by', sa.UUID(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), nullable=False),
    sa.ForeignKeyConstraint(['approved_by'], ['users.id'], name=op.f('fk_report_draft_revisions_approved_by_users'), ondelete='RESTRICT'),
    sa.ForeignKeyConstraint(['patch_proposal_id'], ['report_patch_proposals.id'], name=op.f('fk_report_draft_revisions_patch_proposal_id_report_patch_proposals'), ondelete='SET NULL'),
    sa.ForeignKeyConstraint(['report_id'], ['reports.id'], name=op.f('fk_report_draft_revisions_report_id_reports'), ondelete='RESTRICT'),
    sa.PrimaryKeyConstraint('id', name=op.f('pk_report_draft_revisions'))
    )
    op.add_column('reports', sa.Column('version', sa.Integer(), server_default='1', nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('reports', 'version')
    op.drop_table('report_draft_revisions')
    op.drop_table('report_patch_proposals')
    op.drop_table('report_chat_messages')
    op.drop_table('report_chat_threads')
    # ### end Alembic commands ###
