"""add_created_by_slp_id_and_current_slp_id_to_patient_refs"""

revision = 'ee74ebb16930'
down_revision = '20260610_0013'
branch_labels = None
depends_on = None

from alembic import op
import sqlalchemy as sa



def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('patient_refs', sa.Column('created_by_slp_id', sa.UUID(), nullable=False))
    op.add_column('patient_refs', sa.Column('current_slp_id', sa.UUID(), nullable=False))
    op.create_foreign_key(op.f('fk_patient_refs_created_by_slp_id_users'), 'patient_refs', 'users', ['created_by_slp_id'], ['id'], ondelete='RESTRICT')
    op.create_foreign_key(op.f('fk_patient_refs_current_slp_id_users'), 'patient_refs', 'users', ['current_slp_id'], ['id'], ondelete='RESTRICT')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('fk_patient_refs_current_slp_id_users'), 'patient_refs', type_='foreignkey')
    op.drop_constraint(op.f('fk_patient_refs_created_by_slp_id_users'), 'patient_refs', type_='foreignkey')
    op.drop_column('patient_refs', 'current_slp_id')
    op.drop_column('patient_refs', 'created_by_slp_id')
    # ### end Alembic commands ###
