"""Import ORM models so Alembic can discover metadata reliably."""

from app.models.base import Base
from app.models.entities import (
    AnalysisJob,
    AudioFile,
    LanguageMetrics,
    OntologyConcept,
    OntologyEdge,
    PatientMetricTrend,
    PatientRef,
    RefreshToken,
    Report,
    ReportDraft,
    ReportGenerationEvent,
    ReportGenerationRun,
    ReportSegment,
    Session,
    SoapCaseIndex,
    Template,
    Transcript,
    TranscriptSegment,
    User,
)

__all__ = [
    "AnalysisJob",
    "AudioFile",
    "Base",
    "LanguageMetrics",
    "OntologyConcept",
    "OntologyEdge",
    "PatientMetricTrend",
    "PatientRef",
    "RefreshToken",
    "Report",
    "ReportDraft",
    "ReportGenerationEvent",
    "ReportGenerationRun",
    "ReportSegment",
    "Session",
    "SoapCaseIndex",
    "Template",
    "Transcript",
    "TranscriptSegment",
    "User",
]
